<section class="login">
    <div class="panel panel-primary">
        <div class="panel-heading">Đăng nhập</div>
        <div class="panel-body">
            <?php if($this->error):?>
                <div class="alert alert-warning alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    Tên đăng nhập hoặc mật khẩu không chính xác vui lòng kiểm tra lại.
                </div>
            <?php endif?>
            <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url('login/default', array('controller' => 'index', 'action' => 'index')));
            echo $this->form()->openTag($form);
            ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('user_name')) ?>
                <div class="col-sm-7"><?php
                    echo $this->formElement($form->get('user_name'));
                    ?></div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('password')); ?>
                <div class="col-sm-7"><?php
                    echo $this->formElement($form->get('password'));
                    ?></div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('rememberme')); ?>
                <div class="col-sm-1"><?php
                    echo $this->formElement($form->get('rememberme'));
                    ?></div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6 text-center"><?php
                    echo $this->formElement($form->get('submit'));
                    ?></div>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</section>