<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </div>
    <div class="sidebar sidebar-extent">
          <ul class="nav nav-sidebar">
            <li class="active dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="glyphicon glyphicon-dashboard"></span> Quản trị
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-pushpin"></span> Bài viết</a>
              <ul class="dropdown-menu dropdown-menu-extent" role="menu">
                <li><a href="#">Danh sách</a></li>
                <li><a href="#">Thêm mới</a></li>
              </ul> 
            </li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-list"></span> Chuyên mục</a>
              <ul class="dropdown-menu dropdown-menu-extent" role="menu">
                <li><a href="#">Danh sách</a></li>
                <li><a href="#">Thêm mới</a></li>
              </ul> 
            </li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-tags"></span> Tag</a>
              <ul class="dropdown-menu dropdown-menu-extent" role="menu">
                <li><a href="#">Danh sách</a></li>
                <li><a href="#">Thêm mới</a></li>
              </ul> 
            </li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-picture"></span> Media</a>
              <ul class="dropdown-menu dropdown-menu-extent" role="menu">
                <li><a href="#">Danh sách</a></li>
                <li><a href="#">Thêm mới</a></li>
              </ul> 
            </li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-book"></span> Trang</a>
              <ul class="dropdown-menu dropdown-menu-extent" role="menu">
                <li><a href="#">Danh sách</a></li>
                <li><a href="#">Thêm mới</a></li>
              </ul> 
            </li>
            <li><a href="#"><span class="glyphicon glyphicon-comment"></span> Bình luận</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Người sử dụng</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-globe"></span> Template</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-cog"></span> Cài đặt</a></li>       
            <li><a class = "menu-collapse" href="#"><span class="glyphicon glyphicon-arrow-left"></span> Thu gọn</a></li>         
          </ul>          
        </div>
        <div class="col-sm-1 sidebar sidebar-collapse">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#"><span class="glyphicon glyphicon-dashboard"></span></a></li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-pushpin"></span></a>
              <ul class="dropdown-menu dropdown-menu-collapse" role="menu">
                <li  role="presentation"  class="active"><a href="#">Bài viết</a></li>
                <li role="presentation" class="divider"></li>
                <li><a href="#">Danh sách</a></li>
                <li><a href="#">Thêm mới</a></li>
              </ul> 
            </li>
            <li><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-list"></span></a>
                <ul class="dropdown-menu dropdown-menu-collapse" role="menu">
                <li  role="presentation"  class="active"><a href="#">Chuyên mục</a></li>
                <li role="presentation" class="divider"></li>
                <li><a href="#">Danh sách</a></li>
                <li><a href="#">Thêm mới</a></li>
              </ul> 
            </li>
            <li><a href="#"><span class="glyphicon glyphicon-tags"></span></a></li>
            <li><a href="#"><span class="glyphicon glyphicon-picture"></span></a></li>
            <li><a href="#"><span class="glyphicon glyphicon-book"></span></a></li>
            <li><a href="#"><span class="glyphicon glyphicon-comment"></span></a></li>
            <li><a href="#"><span class="glyphicon glyphicon-user"></span></a></li>
            <li><a href="#"><span class="glyphicon glyphicon-globe"></span></a></li>
            <li><a href="#"><span class="glyphicon glyphicon-cog"></span></a></li>       
            <li><a class = "menu-extent" href="#"><span class="glyphicon glyphicon-arrow-right"></span></a></li>         
          </ul>          
        </div>
    <div class="container-fluid container-content">
      <div class="row">        
        <div class="col-sm-12 col-md-12 main">
          <h1 class="page-header">Hoạt động</h1>
          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
        <!-- /container -->
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/main.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/holder.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')            
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
          
        </script>
    </body>
</html>
