<section class="profile_index">
    <div class="panel panel-default">
        <div class="panel-heading">Thông tin người sử dụng</div>
        <div class="panel-body">
            <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url('admin/default', array('controller' => 'profile', 'action' => 'index')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('role', 'form');
            echo $this->form()->openTag($form);
            ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('userNicename')); ?>
                <div class="col-sm-3"><?php
                    echo $this->formElement($form->get('userNicename'));
                    echo $this->formElementErrors($form->get('userNicename'));
                    ?></div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('userEmail')); ?>
                <div class="col-sm-3"><?php
                    echo $this->formElement($form->get('userEmail'));
                    echo $this->formElementErrors($form->get('userEmail'));
                    ?></div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('userUrl')); ?>
                <div class="col-sm-3"><?php
                    echo $this->formElement($form->get('userUrl'));
                    echo $this->formElementErrors($form->get('userUrl'));
                    ?></div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6 text-center"><?php
                    echo $this->formElement($form->get('send'));
                    ?></div>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</section>