<section class="register">
	<h2>Register</h2>
<?php if($this->error):?>
<p class="error">Tên đăng nhập hoặc mật khẩu không chính xác vui lòng kiểm tra lại</p>
<?php endif?>
<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,array('controller'=>'login','action'=>'index')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
	<dt><?php echo $this->formLabel($form->get('user_name')) ?></dt>
	<dd><?php 
		echo $this->formElement($form->get('user_name'));
		echo $this->formElementErrors($form->get('user_name'));
	?></dd>
	<dt><?php echo $this->formLabel($form->get('password')) ?></dt>
	<dd><?php 
		echo $this->formElement($form->get('password'));
		echo $this->formElementErrors($form->get('password'));
	?></dd>
	<dd><?php 
		echo $this->formElement($form->get('login_btn'));
		echo $this->formElementErrors($form->get('login_btn'));
	?></dd>
</dl>
<?php echo $this->form()->closeTag();?>
</section>