<section class="profile_index">
    <div class="panel panel-default">
        <div class="panel-heading">Thêm mới chuyên mục</div>
        <div class="panel-body">
            <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url('admin/default', array('controller' => 'category', 'action' => 'add')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('role', 'form');
            echo $this->form()->openTag($form);
            ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('cat_name')); ?>
                <div class="col-sm-7"><?php
                    echo $this->formElement($form->get('cat_name'));
                    #echo $this->formElementErrors($form->get('cat_name'));
                    ?></div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('cat_slug')); ?>
                <div class="col-sm-7"><?php
                    echo $this->formElement($form->get('cat_slug'));
                    echo $this->formElementErrors($form->get('cat_slug'));
                    ?></div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('cat_parent_id')); ?>
                <div class="col-sm-7"><?php
                    echo $this->FormSelectUnEscape($form->get('cat_parent_id'));
                    echo $this->formElementErrors($form->get('cat_parent_id'));
                    ?></div>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('cat_desc')); ?>
                <div class="col-sm-7"><?php
                    echo $this->formElement($form->get('cat_desc'));
                    echo $this->formElementErrors($form->get('cat_desc'));
                    ?></div>
            </div>
            <div class="form-group text-center">
                <div class="col-sm-12"><?php
                    echo $this->formElement($form->get('submit'));
                    echo $this->formElementErrors($form->get('submit'));
                    ?></div>
            </div>

            <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</section>