<?php echo $this->content;?>
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/main.js')
    ->prependFile($this->basePath() . '/js/jquery_context_menu/jquery.contextmenu.js')
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/holder.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')            
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
; ?>
<?php echo $this->inlineScript() ?>