<?php
if($this->files){?>
<ol class = "ol_files"><?php
	foreach ($this->files as $key => $value) {?>
	<li class = "file_item">
		<span class = "thumnail filetype-audio"></span>
		<input type = "checkbox" class = "file_select" />
		<em class = "file_ext">mp3</em>
		<a class = "file_option"></a>
		<div class = "info">
			<a class = "link_info_file_item">
				<span class = "file_name"><?php echo $value->getFileName(). $key;?></span>
			</a>
		</div>
	</li>
	<?php
	}
}
?>
<script type = "text/javascript">
	var option = { width: 150
	         ,items: [
	              { text: "Tải về", icon: "ip_16x16_add", alias:"1", action: function(){
	                window.location = urlAdd;
	              } },
	              { text: "Sửa", icon: "ip_16x16_edit", alias:"2", action: function(obj){
	                window.location = urlEdit + '/' + $(obj).find('.taxonomy_id').val();
	              } },
	              { text: "Xóa", icon: "ip_16x16_delete", alias:"4", action: function(obj){
	                window.location = urlDelete + '/' + $(obj).find('.taxonomy_id').val();
	              } },
	            ]
	};
	$(".ol_files li.file_item").contextmenu(option);
	$('li.file_item a.file_option').bind('click', function(){
		$(this).parent().trigger('contextmenu');
	});
</script>