<div id = "folder_header" class = "row">
	<div id = "title" class = "col-md-2">IP-CMS</div>
	<div id = "btn" class = "col-md-4">
		<button type="button" class="btn btn-primary"><span class="upload_file"></span>&nbsp;Tải lên</button>
		<button type="button" class="btn btn-primary"><span class="newfolder"></span></button>
		<button type="button" class="btn btn-primary"><span class="create_text_file"></span></button>
	</div>
	<div id = "search" class = "col-md-6">
		<div class = "row">
			<div class="input-group col-md-10 col-md-offset-2">
	      		<div class="input-group-btn">
	        		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Media type<span class="caret"></span></button>
	        		<ul class="dropdown-menu" role="menu">
			          <li><a href="#">Audio</a></li>
			          <li><a href="#">Image</a></li>
			          <li><a href="#">Video</a></li>
			        </ul>
	      		</div><!-- /btn-group -->
	       		<div class="form-group has-feedback">
				  <label class="control-label sr-only" for="inputSuccess5">Hidden label</label>
				  <input type="text" class="form-control" id="inputSuccess5" placeholder ="Tìm kiếm">
				  <span class="glyphicon glyphicon-search form-control-feedback"></span>
				</div>
				<div class="input-group-btn">
					<button type="button" class="btn btn-default cmd-thumnail"><span class="glyphicon glyphicon-th"></span></button>
					<button type="button" class="btn btn-default cmd-list"><span class="glyphicon glyphicon-list"></span></button>
				</div>
		    </div>
		</div>
    </div>
</div>
<div id = "folder_path" class = "row">
	<ol class="breadcrumb">
	  <li><a href="#"><span class = "folder_open"></span><span class = "folder_name">Quản lý media</span></a></li>
	  <li class="active"><span class = "folder_name"></li>
	</ol>
</div>
<div id = "folder_content" class = "row">
	<div id = "iptree" class = "col-md-2">&nbsp;</div>
	<div id = "file_list"  class = "col-md-10">&nbsp;</div>
</div>
<script type = "text/javascript">
	var urlGetTree = "<?php echo $this->url('media/default', array('controller' => 'index', 'action' => 'getTree')); ?>";
	var urlGetFile = "<?php echo $this->url('media/default', array('controller' => 'index', 'action' => 'getFile')); ?>";
	var sapDir = '<?php echo DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR; ?>';
</script>
